### ISSUE TITLE
Any chance that it plays with Eclipse Che?

### ISSUE THREAD

**Issue by hannpet** [cmorisse/ikp3db#1]
I played with the debugger on cloud9, which worked really well.
Is there any way ikp3dp could interface with Eclipse Che? 
I mean, is any debug-handler in Eclipse Che compatible in the "language that it speaks"- how about GDB?

**Comment by cmorisse** [comment]
Hello,
Thanks for your message and sorry for the late answer.
I had a contact with Stevan Le Meur about that last December. But I have no plan for the moment.

How would you compare the Python editing experience of Che vs Cloud9 ?

Regards,
Cyril
