### ISSUE TITLE
suspend works only once

### ISSUE THREAD

**Issue by kzidane** [cmorisse/ikp3db#7]
Consider this simple program:

```
x = 50
while True:
    pass
```

If you set a breakpoint on the very first line, start the debugger, it stops at the breakpoint as expected. If you then hit Resume then Suspend, it resumes and stops again at some point in the loop as expected, but if you hit resume then suspend again, it resumes but never suspends again unless there's a breakpoint inside the loop. I've been trying to track this down but I couldn't figure out why this happens. Any thoughts?

Thank you!

**Comment by cmorisse** [comment]
There is a bug (or some bugs) in IKPdb state management, I haven't been able to solve...
To ease solving, I worked on a test suite based on IKPdb protocol and valid for IKPdb and IKP3db. 
It's a little bit rough at that point but I will release it soon (this weekend I hope) as an independent repo.
I have another strange breakpoint behaviour I will create a test case that I think is linked to this issue.
May I propose you to add a test case for this issue before we dig to find a solution?
Thanks for your interest in IKPdb !!!!!

**Comment by cmorisse** [comment]
Here is the test suite repository: https://github.com/cmorisse/ikpxdb_tests ! 
But usage instructions are missing...

**Comment by cmorisse** [comment]
I fixed it: https://github.com/cmorisse/ikp3db/commit/41e048e636da533ac136883dbf26cc46aff418da

Here is the test case: https://github.com/cmorisse/ikpxdb_tests/blob/master/test03_2_suspend.py

A few months ago, I switched the Queue used to send command to the debugger by multiprocessing. queue in a move to support multiprocessing debugging.
And this causes this bug as multiprocessing.queue failed to send the 'resume' command (debugged program never resumed)
